[browser]
gatherUsageStats = false

[server]
address = "0.0.0.0"
headless = true
port = 8501

[theme]
base = "light"
primaryColor = "#BC432E"
backgroundColor = "#F8F5F0"
secondaryBackgroundColor = "#EEE7DD"
textColor = "#252525"
font = "sans-serif"
